/*
 * This source file was generated by the Gradle 'init' task
 */

// inside  boopathi@krithik:~/mylearnings/arraypractice2
package demo;

import demo.StudentRunner;
import java.util.Scanner;


public class App {
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Enter your choice :  ");


        if(scanner.hasNextInt()){
            int choice = scanner.nextInt();
            System.out.println("selected choice:" + choice);
            switch(choice){
                case 1 :
                    StudentRunner student1 = new StudentRunner();
                    student1.studentMark();
                    break;
                case 2:
                    StringElement weekDays = new StringElement();
                    weekDays.stringElement();
                    break;
                default:
                    System.out.println("Invalid Option");

            }
        } else{
            System.out.println("Please enter correct number.");
        }
    
        scanner.close();
    }
}


        
              
        
