/*
 * This source file was generated by the Gradle 'init' task
 */
package demo;

import demo.StudentRunner;
public class App {
    
    public static void main(String[] args) {
        StudentRunner student1 = new StudentRunner();
        student1.studentMark();
        
    }
}
